# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#use_frameworks!


target 'BaseProject' do
pod "AFNetworking", "~> 3.0"
pod 'SVProgressHUD'
pod 'SDWebImage’, ‘~> 3.7.2’
pod 'MJRefresh', '~> 3.1.0'
pod 'Masonry'
pod 'AMap2DMap'
pod 'AMapLocation','~>2'
# Mob
pod 'MOBFoundation_IDFA' #Mob产品公共库
pod 'SMSSDK' #SMSSDK必须


pod 'RongCloudIM/IMLib'
pod 'RongCloudIM/IMKit'
pod 'MJExtension'

#分享、第三方登陆
# 主模块(必须)
pod 'ShareSDK3'
# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'ShareSDK3/ShareSDKUI'
# 平台SDK模块(对照一下平台，需要的加上)
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
# 扩展模块（在调用可以弹出我们UI分享方法的时候是必需的）
#pod 'ShareSDK3/ShareSDKExtension'

# Mob
#pod 'MOBFoundation_IDFA'
#pod 'SMSSDK'
#
##分享、第三方登陆
## 主模块(必须)
#pod 'ShareSDK3'
## UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
#pod 'ShareSDK3/ShareSDKUI'
## 平台SDK模块(对照一下平台，需要的加上)
#pod 'ShareSDK3/ShareSDKPlatforms/QQ'
#pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
#pod 'ShareSDK3/ShareSDKPlatforms/WeChat'


end



post_install do |installer|
    
    installer.pods_project.targets.each do |target|
        
        target.build_configurations.each do |config|
            
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            
        end
        
    end
    
end
